kind: Component

configMapGenerator:
- name: derp-config
  literals:
  - DERP_STUN=true
  - DERP_HTTP_PORT=-1
  - DERP_CERT_MODE=manual
  - DERP_CERT_DIR=/etc/derp/certs

resources:
- deployment.yaml
