kind: Deployment
apiVersion: apps/v1
metadata:
  name: overseerr
  labels:
    app: plex
spec:
  selector:
    matchLabels:
      name: overseerr
  template:
    metadata:
      labels:
        name: overseerr
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: plex-pvc
      containers:
        - name: overseerr
          ports:
            - containerPort: 5055
          image: docker.io/sctx/overseerr
          volumeMounts:
            - mountPath: /app/config
              name: data
              subPath: overseerr/config
          env:
            - name: TZ
              value: "America/New_York"
