kind: ConfigMap
apiVersion: v1
metadata:
  name: headscale-config
  namespace: {{ .Release.Namespace }}
data:
{{ (.Files.Glob "configs/headscale/*.yaml").AsConfig | indent 2 }}
  acl.hujson: |
{{ .Files.Get "configs/headscale/acl.hujson" | indent 4 }}
