---
kind: ConfigMap
apiVersion: v1
metadata:
  name: mosquitto-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: home
data:
{{ (.Files.Glob "configs/mosquitto/*").AsConfig | indent 2 }}
