---
kind: ConfigMap
apiVersion: v1
metadata:
  name: headscale-acl
  namespace: {{ .Release.Namespace }}
data:
  acl.hujson: |
    {{- .Values.headscale.acl | nindent 4 }}
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: headscale
  namespace: {{ .Release.Namespace }}
  labels:
    app: home
spec:
  selector:
    matchLabels:
      name: headscale
  template:
    metadata:
      labels:
        name: headscale
    spec:
      tolerations:
        - key: cloud
          operator: Exists
          effect: NoExecute
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: cloud
                operator: In
                values:
                - oracle
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
      - name: config
        configMap:
          name: headscale-config
      - name: acl
        configMap:
          name: headscale-acl
      - name: socket
        emptyDir: {}
      - name: private-key
        secret:
          secretName: headscale-private-key
      containers:
      - name: headscale
        ports:
        - containerPort: 8080
        - containerPort: 3478
        image: docker.io/headscale/headscale:0.16.2
        env:
        - name: GIN_MODE
          value: release
        - name: HEADSCALE_LISTEN_ADDR
          value: "0.0.0.0:8080"
        - name: HEADSCALE_SERVER_URL
          value: {{ .Values.headscale.serverUrl }}
        - name: HEADSCALE_LOG_LEVEL
          value: {{ .Values.headscale.logLevel }}
        - name: HEADSCALE_DB_TYPE
          value: postgres
        - name: HEADSCALE_DB_HOST
          value: postgres-headscale
        - name: HEADSCALE_DB_PORT
          value: "5432"
        - name: HEADSCALE_DB_NAME
          value: headscale
        - name: HEADSCALE_DB_USER
          value: headscale
        - name: HEADSCALE_DB_PASS
          valueFrom:
            secretKeyRef:
              name: postgres-headscale-pw
              key: password
        - name: HEADSCALE_ACL_POLICY_PATH
          value: /var/run/headscale/acl.hujson
        - name: HEADSCALE_PRIVATE_KEY_PATH
          value: /var/run/headscale/private.key
        - name: HEADSCALE_UNIX_SOCKET
          value: /var/run/headscale/headscale.sock
        command: ["headscale", "serve"]
        volumeMounts:
        - name: config
          mountPath: /etc/headscale
        - name: socket
          mountPath: /var/run/headscale
        - name: private-key
          mountPath: /var/run/headscale/private.key
          subPath: key
        - name: acl
          mountPath: /var/run/headscale/acl.hujson
          subPath: acl.hujson
---
kind: Service
apiVersion: v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: headscale-stun
spec:
  type: NodePort
  ipFamilyPolicy: RequireDualStack
  externalTrafficPolicy: Local
  ports:
    - name: stun
      port: 3478
      protocol: UDP
      nodePort: 30478
  selector:
    name: headscale
---
kind: Service
apiVersion: v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: headscale
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    name: headscale
