---
kind: Secret
apiVersion: v1
metadata:
  name: mqtt-auth
  namespace: {{ .Release.Namespace }}
  labels:
    app: home
data:
  passwd.conf: {{ .Values.mqtt.auth | b64enc }}
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: mqtt
  namespace: {{ .Release.Namespace }}
  labels:
    app: home
spec:
  selector:
    matchLabels:
      name: mqtt
  template:
    metadata:
      labels:
        name: mqtt
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: db
          emptyDir: {}
        - name: passwd
          emptyDir: {}
        - name: passwd-conf
          secret:
            secretName: mqtt-auth
        - name: conf
          configMap:
            name: mosquitto-config
      initContainers:
        - name: mqtt-passwd
          image: docker.io/eclipse-mosquitto:1.6.8
          command: ["/bin/sh"]
          args:
            - -c
            - "cp /passwd-conf/* /passwd/ && mosquitto_passwd -U /passwd/passwd.conf"
          volumeMounts:
            - name: passwd
              mountPath: /passwd
            - name: passwd-conf
              mountPath: /passwd-conf
      containers:
        - name: mqtt
          ports:
            - containerPort: 1883
          image: docker.io/eclipse-mosquitto:1.6.8
          volumeMounts:
            - name: db
              mountPath: /var/lib/mosquitto
            - name: conf
              mountPath: /mosquitto/config
            - name: passwd
              mountPath: /passwd
---
kind: Service
apiVersion: v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: mqtt
  annotations:
    {{- toYaml .Values.mqtt.service.annotations | nindent 4 }}
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: mqtt
      port: 1883
      protocol: TCP
      targetPort: 1883
  selector:
    name: mqtt
