---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: registry
  namespace: {{ .Release.Namespace }}
  labels:
    app: home
spec:
  selector:
    matchLabels:
      name: registry
  template:
    metadata:
      labels:
        name: registry
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: home-pvc
      containers:
        - name: registry
          ports:
            - containerPort: 5000
          image: docker.io/registry:2
          volumeMounts:
            - mountPath: /var/lib/registry
              name: data
              subPath: registry
---
kind: Service
apiVersion: v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: registry
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    name: registry
