---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebrowser
  namespace: {{ .Release.Namespace }}
  labels:
    app: home
spec:
  selector:
    matchLabels:
      name: filebrowser
  template:
    metadata:
      labels:
        name: filebrowser
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: home-pvc
      containers:
        - name: filebrowser
          image: docker.io/filebrowser/filebrowser
          ports:
            - containerPort: 8080
          env:
            - name: FB_ADDRESS
              value: "0.0.0.0"
            - name: FB_PORT
              value: "8080"
            - name: FB_DATABASE
              value: /db/database.db
            - name: FB_ROOT
              value: /srv
          volumeMounts:
            - name: data
              mountPath: /srv
              subPath: filebrowser/srv
            - name: data
              mountPath: /db
              subPath: filebrowser/db
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: filebrowser
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    name: filebrowser
