---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: headscale
  namespace: {{ .Release.Namespace }}
  labels:
    app: home
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: headscale
  template:
    metadata:
      labels:
        name: headscale
    spec:
      tolerations:
        - key: cloud
          operator: Exists
          effect: NoExecute
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: cloud
                operator: Exists
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: db
          persistentVolumeClaim:
            claimName: cloud-pvc
        - name: config
          configMap:
            name: headscale-config
        - name: socket
          emptyDir: {}
      containers:
        - name: headscale
          ports:
            - containerPort: 8080
            - containerPort: 30478
          image: docker.io/headscale/headscale:0.15.0
          env:
            - name: GIN_MODE
              value: release
          command: ["headscale"]
          args:
            - serve
          volumeMounts:
            - mountPath: /var/lib/headscale
              name: db
              subPath: headscale
            - mountPath: /etc/headscale
              name: config
            - mountPath: /var/run/headscale
              name: socket
---
kind: Service
apiVersion: v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: headscale-stun
spec:
  type: NodePort
  ipFamilyPolicy: RequireDualStack
  externalTrafficPolicy: Local
  ports:
    - name: stun
      port: 30478
      protocol: UDP
      nodePort: 30478
  selector:
    name: headscale
---
kind: Service
apiVersion: v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: headscale
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    name: headscale
