---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: minio
  namespace: {{ .Release.Namespace }}
  labels:
    app: home
spec:
  selector:
    matchLabels:
      name: minio
  template:
    metadata:
      labels:
        name: minio
    spec:
      securityContext:
        fsGroup: 2000
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: home-pvc
      containers:
        - name: minio
          ports:
            - containerPort: 9000
            - containerPort: 9001
          image: quay.io/minio/minio:RELEASE.2022-09-01T23-53-36Z
          command: ["minio", "server", "/data", "--console-address", ":9001"]
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: user
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: password
          volumeMounts:
            - mountPath: /data
              name: data
              subPath: minio
---
kind: Service
apiVersion: v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: minio
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 9000
  selector:
    name: minio
---
kind: Service
apiVersion: v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: minio-console
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 9001
  selector:
    name: minio
