---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: adguard
  namespace: {{ .Release.Namespace }}
  labels:
    app: home
spec:
  selector:
    matchLabels:
      name: adguard
  template:
    metadata:
      labels:
        name: adguard
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: home-pvc
      containers:
        - name: adguard
          ports:
            - containerPort: 53
            - containerPort: 80
          image: docker.io/adguard/adguardhome
          volumeMounts:
            - mountPath: /opt/adguardhome/work
              name: data
              subPath: adguard/work
            - mountPath: /opt/adguardhome/conf
              name: data
              subPath: adguard/conf
---
kind: Service
apiVersion: v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: adguard-dns-udp
  annotations:
    metallb.universe.tf/allow-shared-ip: "adguard-{{ .Values.adguard.loadBalancerIP }}"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  loadBalancerIP: {{ .Values.adguard.loadBalancerIP }}
  ports:
    - name: dns-udp
      port: 53
      protocol: UDP
      targetPort: 53
  selector:
    name: adguard
---
kind: Service
apiVersion: v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: adguard-dns-tcp
  annotations:
    metallb.universe.tf/allow-shared-ip: "adguard-{{ .Values.adguard.loadBalancerIP }}"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  loadBalancerIP: {{ .Values.adguard.loadBalancerIP }}
  ports:
    - name: dns-tcp
      port: 53
      protocol: TCP
      targetPort: 53
  selector:
    name: adguard
---
kind: Service
apiVersion: v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: adguard
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    name: adguard
