apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-headscale
  namespace: {{ .Release.Namespace }}
spec:
  serviceName: postgres-headscale
  selector:
    matchLabels:
      name: postgres-headscale
  template:
    metadata:
      labels:
        name: postgres-headscale
    spec:
      tolerations:
        - key: cloud
          operator: Exists
          effect: NoExecute
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: cloud
                operator: In
                values:
                - oracle
      containers:
      - name: postgres-headscale
        image: docker.io/postgres:14.5-alpine
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-headscale-pw
              key: password
        - name: POSTGRES_USER
          value: headscale
        - name: POSTGRES_DB
          value: headscale
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
          subPath: data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: oci-bv-encrypted
      resources:
        requests:
          storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-headscale
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 5432
    name: pg
  selector:
    name: postgres-headscale
