stages:
- containers

.build-image-template:
  stage: containers
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - |
      mkdir -p /kaniko/.docker && \
        echo '{
          "auths": {
            "https://'"$HOMELAB_REGISTRY"'": {
              "username": "'"$HOMELAB_REGISTRY_USER"'",
              "password": "'"$HOMELAB_REGISTRY_PASSWORD"'"
            }
          }
        }' > /kaniko/.docker/config.json
    - |
      /kaniko/executor \
      --context $CONTEXT_DIR \
      --dockerfile $DOCKERFILE \
      --cache=true \
      --destination $HOMELAB_REGISTRY/$IMAGE_NAME

build-cups:
  extends:
    - .build-image-template
  variables:
    IMAGE_NAME: cups-brother
    CONTEXT_DIR: ./containers/cups-brother
    DOCKERFILE: ./containers/cups-brother/Dockerfile

build-ssh-client:
  extends:
    - .build-image-template
  variables:
    IMAGE_NAME: ssh-client
    CONTEXT_DIR: ./containers/ssh-client
    DOCKERFILE: ./containers/ssh-client/Dockerfile
