stages:
- containers

.build-image-template:
  stage: containers
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - |
      DESTINATION="--destination $HOMELAB_REGISTRY/$IMAGE_NAME:sha-$CI_COMMIT_SHORT_SHA"
      if [[ "$CI_COMMIT_BRANCH" = "$CI_DEFAULT_BRANCH" ]]; then
        DESTINATION="$DESTINATION --destination $HOMELAB_REGISTRY/$IMAGE_NAME:latest"
      fi
      mkdir -p /kaniko/.docker && \
        echo '{
          "auths": {
            "https://'"$HOMELAB_REGISTRY"'": {
              "username": "'"$HOMELAB_REGISTRY_USER"'",
              "password": "'"$HOMELAB_REGISTRY_PASSWORD"'"
            }
          }
        }' > /kaniko/.docker/config.json
    - |
      /kaniko/executor \
      --context $CONTEXT_DIR \
      --dockerfile $DOCKERFILE \
      --cache=true \
      $DESTINATION

build-cups:
  extends:
    - .build-image-template
  variables:
    IMAGE_NAME: cups-brother
    CONTEXT_DIR: ./containers/cups-brother
    DOCKERFILE: ./containers/cups-brother/Dockerfile
  rules:
    - changes:
        - containers/cups-brother/**/*

build-ssh-client:
  extends:
    - .build-image-template
  variables:
    IMAGE_NAME: ssh-client
    CONTEXT_DIR: ./containers/ssh-client
    DOCKERFILE: ./containers/ssh-client/Dockerfile
  rules:
    - changes:
        - containers/ssh-client/**/*
