repositories:
- name: metallb
  url: https://metallb.github.io/metallb
- name: ingress-nginx
  url: https://kubernetes.github.io/ingress-nginx
- name: external-dns
  url: https://kubernetes-sigs.github.io/external-dns/
- name: nvidia
  url: https://helm.ngc.nvidia.com/nvidia
- name: coredns
  url: https://coredns.github.io/helm
- name: jetstack
  url: https://charts.jetstack.io
- name: k8s-at-home
  url: https://k8s-at-home.com/charts/

releases:
- name: coredns
  labels:
    app: coredns
    system: base
  namespace: kube-system
  chart: coredns/coredns
  version: 1.19.4
  values:
  - service:
      # default for k3s
      clusterIP: 10.43.0.10
    # helm show values coredns/coredns
    # adding k8s_external here
    servers:
    - zones:
      - zone: .
      port: 53
      # If serviceType is nodePort you can specify nodePort here
      # nodePort: 30053
      plugins:
      - name: errors
      # Serves a /health endpoint on :8080, required for livenessProbe
      - name: health
        configBlock: |-
          lameduck 5s
      # Serves a /ready endpoint on :8181, required for readinessProbe
      - name: ready
      # Required to query kubernetes API for data
      - name: kubernetes
        parameters: cluster.local in-addr.arpa ip6.arpa
        configBlock: |-
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
          ttl 30
      - name: k8s_external
        parameters: k8s.lan
      # Serves a /metrics endpoint on :9153, required for serviceMonitor
      - name: prometheus
        parameters: 0.0.0.0:9153
      - name: forward
        parameters: . 1.1.1.1
      - name: cache
        parameters: 30
      - name: loop
      - name: reload
      - name: loadbalance

- name: metallb
  labels:
    app: metallb
    system: base
  namespace: metallb-system
  createNamespace: true
  chart: metallb/metallb
  version: 0.13.4
  values:
  - speaker:
      tolerations:
      - key: cloud
        operator: Exists
        effect: NoExecute

- name: ingress-nginx-cloud
  labels:
    app: ingress-nginx-cloud
    system: access
  namespace: ingress-nginx-cloud
  createNamespace: true
  chart: ingress-nginx/ingress-nginx
  version: 4.2.0
  values:
  - controller:
      ingressClassResource:
        default: false
        name: nginx-cloud
        controllerValue: k8s.io/ingress-nginx-cloud
      service:
        enabled: true
        annotations:
          metallb.universe.tf/address-pool: cloud
          metallb.universe.tf/allow-shared-ip: cloud
        externalTrafficPolicy: Local
      ingressClass: nginx-cloud
      nodeSelector:
        kubernetes.io/hostname: cloud
      tolerations:
      - key: cloud
        operator: Exists
        effect: NoExecute
      dnsPolicy: ClusterFirstWithHostNet
      kind: DaemonSet
      publishService:
        enabled: true

- name: ingress-nginx-lan
  labels:
    app: ingress-nginx-lan
    system: access
  namespace: ingress-nginx-lan
  createNamespace: true
  chart: ingress-nginx/ingress-nginx
  version: 4.2.0
  values:
  - controller:
      ingressClassResource:
        default: true
        name: nginx-lan
        controllerValue: k8s.io/ingress-nginx-lan
      service:
        enabled: true
        annotations:
          metallb.universe.tf/address-pool: skynet
        externalTrafficPolicy: Local
      dnsPolicy: ClusterFirstWithHostNet
      kind: DaemonSet
      publishService:
        enabled: true

- name: ingress-nginx-wg
  labels:
    app: ingress-nginx-wg
    system: access
  namespace: ingress-nginx-wg
  createNamespace: true
  chart: ingress-nginx/ingress-nginx
  version: 4.2.0
  values:
  - controller:
      ingressClassResource:
        default: false
        name: nginx-wg
        controllerValue: k8s.io/ingress-nginx-wg
      service:
        enabled: true
        annotations:
          metallb.universe.tf/allow-shared-ip: "tailscale"
        loadBalancerIP: 100.64.0.6
      nodeSelector:
        kubernetes.io/hostname: videx
      dnsPolicy: ClusterFirstWithHostNet
      kind: DaemonSet
      publishService:
        enabled: true

- name: gpu-operator
  labels:
    app: gpu-operator
    system: base
  namespace: gpu-operator
  chart: nvidia/gpu-operator
  createNamespace: true
  version: v1.11.0
  set:
    - name: driver.enabled
      value: false
    - name: toolkit.enabled
      value: false

- name: librespeed
  labels:
    app: librespeed
    system: apps
  namespace: home
  chart: k8s-at-home/librespeed
  createNamespace: true
  version: 5.3.2
  values:
  - service:
      main:
        type: LoadBalancer
        annotations:
          metallb.universe.tf/address-pool: skynet

    nodeSelector:
      kubernetes.io/hostname: cloud
    tolerations:
      - key: cloud
        operator: Exists
        effect: NoExecute

- name: external-dns
  labels:
    app: external-dns
    system: access
  namespace: external-dns
  chart: external-dns/external-dns
  createNamespace: true
  version: 1.10.1
  values:
  - provider: cloudflare
    logLevel: debug
    txtOwnerId: k8s
    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: cloudflare-token
            key: token

- name: cert-manager
  labels:
    app: cert-manager
    system: base
  namespace: cert-manager
  chart: jetstack/cert-manager
  createNamespace: true
  version: v1.8.1
  set:
    - name: installCRDs
      value: true

- name: utils
  namespace: default
  chart: ./utils/
  values:
    - ./values/utils.yaml

- name: home
  namespace: home
  chart: ./home/
  values:
    - ./values/home.yaml

- name: plex
  namespace: plex
  chart: ./plex/
  values:
    - ./values/plex.yaml
