---
apiVersion: v1
kind: ConfigMap
metadata:
  name: private-dns-entrypoint
  namespace: kube-system
data:
  dns.gotmpl: |-
{{ .Files.Get "configs/private-dns/dns.gotmpl" | indent 4 }}
  entrypoint.sh: |-
    #!/bin/bash
    HOSTS="$(kubectl get ing,svc -A -o go-template-file=/data/dns.gotmpl)"
    kubectl create cm \
      -n kube-system \
      --dry-run=client \
      private-dns-hosts \
      --from-literal=hosts="$HOSTS" -o yaml | \
      kubectl apply -f -
