---
apiVersion: v1
kind: ConfigMap
metadata:
  name: private-dns-entrypoint
  namespace: kube-system
data:
  dns.gotmpl: |-
{{ .Files.Get "configs/private-dns/dns.gotmpl" | indent 4 }}
  entrypoint.sh: |-
{{ .Files.Get "configs/private-dns/entrypoint.sh" | indent 4 }}
