---
kind: Service
apiVersion: v1
metadata:
  namespace: {{ .Values.coredns.namespace }}
  name: coredns-dns-udp
  annotations:
    metallb.universe.tf/allow-shared-ip: "coredns-dns-{{ .Values.coredns.loadBalancerIP }}"
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.coredns.loadBalancerIP }}
  ports:
    - name: dns-udp
      port: 53
      protocol: UDP
      targetPort: 53
  selector:
    app.kubernetes.io/instance: coredns
    app.kubernetes.io/name: coredns
    k8s-app: coredns
---
kind: Service
apiVersion: v1
metadata:
  namespace: {{ .Values.coredns.namespace }}
  name: coredns-dns-tcp
  annotations:
    metallb.universe.tf/allow-shared-ip: "coredns-dns-{{ .Values.coredns.loadBalancerIP }}"
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.coredns.loadBalancerIP }}
  ports:
    - name: dns-tcp
      port: 53
      protocol: TCP
      targetPort: 53
  selector:
    app.kubernetes.io/instance: coredns
    app.kubernetes.io/name: coredns
    k8s-app: coredns
