{{- range $key, $val := .Values.metallb.pools }}
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: {{ $key }}
  namespace: metallb-system
spec:
  {{- toYaml $val | nindent 2 }}
{{- end }}
{{- range $key, $val := .Values.metallb.l2advertisements }}
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: {{ $key }}
  namespace: metallb-system
spec:
  {{- toYaml $val | nindent 2 }}
{{- end }}
