---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
  namespace: {{ .Values.certmanager.namespace }}
type: Opaque
stringData:
  api-token: {{ .Values.certmanager.cloudflareAPIToken }}
