---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
{{- $storageHost := .Values.storageHost }}
{{- range $key, $val := .Values.persistence }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $key }}-pv
  namespace: {{ $key }}
spec:
  capacity:
    storage: {{ $val.size }}
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
    - ReadWriteOnce
    - ReadOnlyMany
  nfs:
    server: {{ $val.server }}
    path: {{ $val.path }}
{{- end }}
