namespace: home

components:
- ../../apps/adguard

configMapGenerator:
- name: adguard-config
  behavior: replace
  files:
  - config/AdGuardHome.yaml

patchesStrategicMerge:
- |-
  apiVersion: v1
  kind: Service
  metadata:
    name: adguard
  spec:
    type: LoadBalancer
    loadBalancerIP: 192.168.1.53

resources:
- config/ingress.yaml
