apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gpu-operator
spec:
  chart:
    spec:
      chart: gpu-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: nvidia
        namespace: flux-system
      version: v22.9.1
  interval: 24h
  valuesFrom:
  - kind: ConfigMap
    name: gpu-operator-values-common
    valuesKey: values.yaml
  - kind: ConfigMap
    name: gpu-operator-values-env
    valuesKey: values.yaml
