unifi:
  # wifi ap inform
  loadBalancerIP: 192.168.1.254

hass:
  # wemo upnp needs to be in same subnet
  pywemoLoadBalancerIP: 192.168.4.200

adguard:
  loadBalancerIP: 192.168.1.53

podSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000
  runAsNonRoot: true
