namespace: external-dns

secretGenerator:
- name: cloudflare-token
  envs:
  - config/cloudflare-token.env

helmCharts:
- name: external-dns
  releaseName: external-dns
  version: 1.10.1
  repo: https://kubernetes-sigs.github.io/external-dns
  valuesInline:
    provider: cloudflare
    logLevel: debug
    txtOwnerId: k8s
    extraArgs:
      # only create records for service/ingress with this annotation
      - "--annotation-filter=sclem.dev/external-dns"
    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: cloudflare-token
            key: token
