namespace: external-dns

components:
- ../../apps/external-dns

secretGenerator:
- name: cloudflare-token
  envs:
  - config/cloudflare-token.env
  options:
    disableNameSuffixHash: true

configMapGenerator:
- name: external-dns-values-env
  files:
  - values.yaml
