provider: cloudflare
logLevel: debug
txtOwnerId: k8s
extraArgs:
  # only create records for service/ingress with this annotation
  - "--annotation-filter=sclem.dev/external-dns"
env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-token
        key: token
