kind: Service
apiVersion: v1
metadata:
  name: mqtt
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: mqtt
      port: 1883
      protocol: TCP
      targetPort: 1883
  selector:
    name: mqtt
