image:
  tag: 1.28.4
persistence:
  data:
    enabled: true
    accessMode: ReadWriteOnce
    storageClass: local-storage
    size: 1Gi
  usb:
    enabled: true
    type: hostPath
    # udev rule on host
    #SUBSYSTEM=="tty",ENV{ID_VENDOR}=="ITEAD",ENV{ID_MODEL}=="SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2",ENV{ID_SERIAL_SHORT}=="20220817114419",SYMLINK+="sonoff0"
    hostPath: /dev/sonoff0
    hostPathType: CharDevice
    mountPath: /dev/zigbee0
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - sailbox
securityContext:
  privileged: true
config:
  advanced:
    channel: 20
  homeassistant: true
  mqtt:
    base_topic: zigbee2mqtt
    server: 'mqtt://mqtt'
  serial:
    port: /dev/zigbee0
    adapter: ezsp
