kind: Component

secretGenerator:
- name: headscale-private-key
  literals:
  - key=
  - noise-key=
- name: headscale-env
  literals:
  - HEADSCALE_LOG_LEVEL=debug

configMapGenerator:
- name: headscale-config
  literals:
  - config.yaml=
  - acl.yaml=
  - derpmap.yaml=
- name: headscale-env
  literals: []

resources:
- ./deployment.yaml
- ./service.yaml
