namespace: monitoring

configMapGenerator:
- name: grafana-domain
  envs:
  - config/domain.env

configurations:
- configuration.yaml

resources:
- service.yaml
- deployment.yaml
- pvc.yaml
- ingress.yaml

replacements:
- source:
    kind: ConfigMap
    name: grafana-domain
    fieldPath: data.DOMAIN
  targets:
  - select:
      kind: Ingress
      name: grafana
    fieldPaths:
    - spec.rules.0.host
    - spec.tls.0.hosts.0
    options:
      create: true
