namespace: kube-system

secretGenerator:
- name: oci-volume-provisioner
  files:
  - config.yaml=config/cloud-provider.yaml

resources:
- https://github.com/oracle/oci-cloud-controller-manager/releases/download/v1.23.0/oci-csi-controller-driver.yaml
- https://github.com/oracle/oci-cloud-controller-manager/releases/download/v1.23.0/oci-csi-node-driver.yaml
- https://github.com/oracle/oci-cloud-controller-manager/releases/download/v1.23.0/oci-csi-node-rbac.yaml
- https://github.com/oracle/oci-cloud-controller-manager/releases/download/v1.23.0/storage-class.yaml

patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: csi-oci-controller
    namespace: kube-system
  spec:
    template:
      spec:
        tolerations:
          - key: cloud
            operator: Exists
            effect: NoExecute
        nodeSelector:
          cloud: oracle
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: cloud
                  operator: In
                  values:
                  - oracle
- |-
  apiVersion: apps/v1
  kind: DaemonSet
  metadata:
    name: csi-oci-node
    namespace: kube-system
  spec:
    template:
      spec:
        tolerations:
          - key: cloud
            operator: Exists
            effect: NoExecute
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: cloud
                  operator: In
                  values:
                  - oracle
patchesJSON6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: csi-oci-controller
  patch: |-
    - op: replace
      path: /spec/template/spec/nodeSelector
      value: {}
