helmCharts:
- name: librespeed
  releaseName: librespeed
  version: 5.3.2
  repo: https://k8s-at-home.com/charts/
  valuesInline:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: cloud
              operator: Exists
    service:
      main:
        type: LoadBalancer
        annotations:
          metallb.universe.tf/address-pool: skynet
    tolerations:
      - key: cloud
        operator: Exists
        effect: NoExecute
