kind: Deployment
apiVersion: apps/v1
metadata:
  name: radarr
  labels:
    app: plex
spec:
  selector:
    matchLabels:
      name: radarr
  template:
    metadata:
      labels:
        name: radarr
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: plex-pvc
      containers:
        - name: radarr
          ports:
            - containerPort: 7878
          image: ghcr.io/onedr0p/radarr:4.3.2.6857
          volumeMounts:
            - mountPath: /config
              name: data
              subPath: radarr/config
            - mountPath: /downloads
              name: data
              subPath: transmission/downloads/complete
            - mountPath: /movies
              name: data
              subPath: plex/data/movies
          env:
            - name: TZ
              value: "America/New_York"
