plex:
  # secondary service for tailscale
  loadBalancerIP: 100.64.0.6

transmission:
  env: []

vpn:
  secret:
    name: vpn-wg-conf
    configKey: conf
    portKey: forward_port
  livenessProbeHost: google.com

podSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000
  runAsNonRoot: true

ingress:
  plex:
    - host: plex.example.com
      class: nginx-lan
