apiVersion: v1
kind: Service
metadata:
  name: unifi
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8443
  - port: 8843
    targetPort: 8843
    name: https-redirect
    protocol: TCP
  - port: 8880
    targetPort: 8880
    name: http-redirect
    protocol: TCP
  - port: 6789
    targetPort: 6789
    name: throughput-measurement
    protocol: TCP
  - port: 8080
    targetPort: 8080
    name: uap-inform
    protocol: TCP
  - port: 3478
    targetPort: 3478
    name: stun-port
    protocol: UDP
  - port: 10001
    targetPort: 10001
    name: ap-discovery
    protocol: UDP
  - port: 1900
    targetPort: 1900
    name: ubnt-1900
    protocol: UDP
  - port: 5514
    targetPort: 5514
    name: ubnt-5514
    protocol: UDP
  selector:
    name: unifi
