controller:
  service:
    enabled: true
    externalTrafficPolicy: Local
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "10254"
  metrics:
    enabled: true
  kind: DaemonSet
  publishService:
    enabled: true
