apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 3Ti
  claimRef:
    kind: PersistentVolumeClaim
    name: minio
    namespace: storage
  local:
    path: /data/raid/k8s/minio
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: sclem.dev/storage-host
          operator: Exists
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem
