---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: radarr
  namespace: {{ .Release.Namespace }}
  labels:
    app: plex
spec:
  selector:
    matchLabels:
      name: radarr
  template:
    metadata:
      labels:
        name: radarr
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: plex-pvc
      containers:
        - name: radarr
          ports:
            - containerPort: 7878
          image: ghcr.io/k8s-at-home/radarr
          volumeMounts:
            - mountPath: /config
              name: data
              subPath: radarr/config
            - mountPath: /downloads
              name: data
              subPath: transmission/downloads/complete
            - mountPath: /movies
              name: data
              subPath: plex/data/movies
          env:
            - name: TZ
              value: "America/New_York"
---
kind: Service
apiVersion: v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: radarr
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 7878
  selector:
    name: radarr
