---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: overseerr
  namespace: {{ .Release.Namespace }}
  labels:
    app: plex
spec:
  selector:
    matchLabels:
      name: overseerr
  template:
    metadata:
      labels:
        name: overseerr
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: plex-pvc
      containers:
        - name: overseerr
          ports:
            - containerPort: 5055
          image: docker.io/sctx/overseerr
          volumeMounts:
            - mountPath: /app/config
              name: data
              subPath: overseerr/config
          env:
            - name: TZ
              value: "America/New_York"
---
kind: Service
apiVersion: v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: overseerr
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 5055
  selector:
    name: overseerr
