---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: transmission
  namespace: {{ .Release.Namespace }}
  labels:
    app: plex
spec:
  selector:
    matchLabels:
      name: transmission
  template:
    metadata:
      labels:
        name: transmission
    spec:
      volumes:
        - name: wg-conf
          secret:
            secretName: {{ .Values.vpn.secret.name }}
        - name: data
          persistentVolumeClaim:
            claimName: plex-pvc
      initContainers:
        - name: flood-ui
          image: curlimages/curl:7.76.1
          command:
          - "/bin/sh"
          - "-c"
          - "test ! -d /config/flood-for-transmission && curl -o- -sL https://github.com/johman10/flood-for-transmission/releases/download/latest/flood-for-transmission.tar.gz | tar xzf - -C /config || exit 0"
          volumeMounts:
          - name: data
            mountPath: /config
            subPath: transmission/config
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
      containers:
        - name: vpn
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - SYS_MODULE
            privileged: true
          image: ghcr.io/k8s-at-home/wireguard
          volumeMounts:
            - mountPath: /etc/wireguard/wg0.conf
              name: wg-conf
              subPath: {{ .Values.vpn.secret.configKey }}
          livenessProbe:
            exec:
              command:
                - ping
                - -c1
                - "-4"
                - {{ .Values.vpn.livenessProbeHost }}
            failureThreshold: 1
            initialDelaySeconds: 30
            periodSeconds: 300
            successThreshold: 1
            timeoutSeconds: 5
        - name: transmission
          image: ghcr.io/k8s-at-home/transmission
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          ports:
            - containerPort: 9091
          env:
            - name: TRANSMISSION_SPEED_LIMIT_UP_ENABLED
              value: "true"
            - name: TRANSMISSION_PEER_PORT
              valueFrom:
                {{- with .Values.vpn.secret }}
                secretKeyRef:
                  name: {{ .name }}
                  key: {{ .portKey }}
                {{- end }}
            - name: TRANSMISSION_WEB_HOME
              value: /config/flood-for-transmission/
            - name: TZ
              value: "America/New_York"
          volumeMounts:
            - mountPath: /config
              name: data
              subPath: transmission/config
            - mountPath: /downloads
              name: data
              subPath: transmission/downloads
---
kind: Service
apiVersion: v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: transmission
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 9091
  selector:
    name: transmission
