---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: tautulli
  namespace: {{ .Release.Namespace }}
  labels:
    app: plex
spec:
  selector:
    matchLabels:
      name: tautulli
  template:
    metadata:
      labels:
        name: tautulli
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: plex-pvc
      containers:
        - name: tautulli
          ports:
            - containerPort: 8181
          image: ghcr.io/k8s-at-home/tautulli
          volumeMounts:
            - mountPath: /config
              name: data
              subPath: tautulli/config
          env:
            - name: TZ
              value: "America/New_York"
---
kind: Service
apiVersion: v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: tautulli
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8181
  selector:
    name: tautulli
