---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: tautulli
  namespace: {{ .Release.Namespace }}
  labels:
    app: plex
spec:
  selector:
    matchLabels:
      name: tautulli
  template:
    metadata:
      labels:
        name: tautulli
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: plex-pvc
      containers:
        - name: tautulli
          ports:
            - containerPort: 8181
          image: docker.io/linuxserver/tautulli
          volumeMounts:
            - mountPath: /config
              name: data
              subPath: tautulli/config
          env:
            - name: PUID
              value: "0"
            - name: PGID
              value: "0"
            - name: TZ
              value: "America/New_York"
---
kind: Service
apiVersion: v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: tautulli
  annotations:
    metallb.universe.tf/address-pool: vlan-main
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8181
  selector:
    name: tautulli
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plex-tautulli-ingress-tls
  namespace: {{ .Release.Namespace }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - tautulli.wg.sclem.dev
      secretName: letsencrypt-tautulli
  rules:
  - host: tautulli.wg.sclem.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: tautulli
            port:
              name: http
