---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: bazarr
  namespace: {{ .Release.Namespace }}
  labels:
    app: plex
spec:
  selector:
    matchLabels:
      name: bazarr
  template:
    metadata:
      labels:
        name: bazarr
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: plex-pvc
      containers:
        - name: bazarr
          ports:
            - containerPort: 6767
          image: ghcr.io/k8s-at-home/bazarr
          volumeMounts:
            - mountPath: /config
              name: data
              subPath: bazarr/config
            - mountPath: /tv
              name: data
              subPath: plex/data/tvshows
            - mountPath: /movies
              name: data
              subPath: plex/data/movies
          env:
            - name: TZ
              value: "America/New_York"
---
kind: Service
apiVersion: v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: bazarr
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 6767
  selector:
    name: bazarr
