---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: radarr
  namespace: {{ .Release.Namespace }}
  labels:
    app: plex
spec:
  selector:
    matchLabels:
      name: radarr
  template:
    metadata:
      labels:
        name: radarr
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: plex-pvc
      containers:
        - name: radarr
          ports:
            - containerPort: 7878
          image: docker.io/linuxserver/radarr
          volumeMounts:
            - mountPath: /config
              name: data
              subPath: radarr/config
            - mountPath: /downloads
              name: data
              subPath: transmission/downloads/complete
            - mountPath: /movies
              name: data
              subPath: plex/data/movies
          env:
            - name: PUID
              value: "0"
            - name: PGID
              value: "0"
            - name: TZ
              value: "America/New_York"
---
kind: Service
apiVersion: v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: radarr
  annotations:
    metallb.universe.tf/address-pool: vlan-main
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 7878
  selector:
    name: radarr
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plex-radarr-ingress-tls
  namespace: {{ .Release.Namespace }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - radarr.wg.sclem.dev
      secretName: letsencrypt-radarr
  rules:
  - host: radarr.wg.sclem.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: radarr
            port:
              name: http
