---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: transmission
  namespace: {{ .Release.Namespace }}
  labels:
    app: plex
spec:
  selector:
    matchLabels:
      name: transmission
  template:
    metadata:
      labels:
        name: transmission
    spec:
      volumes:
        - name: config
          secret:
            secretName: {{ .Values.vpn.secret.name }}
        - name: data
          persistentVolumeClaim:
            claimName: plex-pvc
        - name: modules
          hostPath:
            path: /lib/modules
      containers:
        - name: vpn
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
            privileged: true
          image: lscr.io/linuxserver/wireguard
          volumeMounts:
            - mountPath: /config/wg0.conf
              name: config
              subPath: {{ .Values.vpn.secret.configKey }}
            - mountPath: /lib/modules
              name: modules
          env:
            - name: TZ
              value: "America/New_York"
          livenessProbe:
            {{- toYaml .Values.vpn.livenessProbe | nindent 12 }}
        - name: transmission
          image: docker.io/linuxserver/transmission
          ports:
            - containerPort: 9091
          env:
            - name: PEERPORT
              valueFrom:
                {{- with .Values.vpn.secret }}
                secretKeyRef:
                  name: {{ .name }}
                  key: {{ .portKey }}
                {{- end }}
            - name: TRANSMISSION_WEB_HOME
              value: /flood-for-transmission/
            - name: TZ
              value: "America/New_York"
            - name: PUID
              value: "0"
            - name: PGID
              value: "0"
          volumeMounts:
            - mountPath: /config
              name: data
              subPath: transmission/config
            - mountPath: /downloads
              name: data
              subPath: transmission/downloads
            - mountPath: /watch
              name: data
              subPath: transmission/watch
---
kind: Service
apiVersion: v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: transmission
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 9091
  selector:
    name: transmission
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: transmission-ingress-tls
  namespace: {{ .Release.Namespace }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx-wg
  tls:
    - hosts:
        - transmission.wg.sclem.dev
      secretName: letsencrypt-transmission
  rules:
  - host: transmission.wg.sclem.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: transmission
            port:
              name: http
