---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: requestrr
  namespace: {{ .Release.Namespace }}
  labels:
    app: plex
spec:
  selector:
    matchLabels:
      name: requestrr
  template:
    metadata:
      labels:
        name: requestrr
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: plex-pvc
      containers:
        - name: requestrr
          ports:
            - containerPort: 4545
          image: docker.io/darkalfx/requestrr:v2.1.2
          volumeMounts:
            - mountPath: /root/config
              name: data
              subPath: requestrr/config
          env:
            - name: TZ
              value: "America/New_York"
---
kind: Service
apiVersion: v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: requestrr
  annotations:
    metallb.universe.tf/address-pool: vlan-main
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 4545
  selector:
    name: requestrr
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plex-requestrr-ingress-tls
  namespace: {{ .Release.Namespace }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - requestrr.wg.sclem.dev
      secretName: letsencrypt-requestrr
  rules:
  - host: requestrr.wg.sclem.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: requestrr
            port:
              name: http
