---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: bazarr
  namespace: {{ .Release.Namespace }}
  labels:
    app: plex
spec:
  selector:
    matchLabels:
      name: bazarr
  template:
    metadata:
      labels:
        name: bazarr
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: plex-pvc
      containers:
        - name: bazarr
          ports:
            - containerPort: 6767
          image: docker.io/linuxserver/bazarr
          volumeMounts:
            - mountPath: /config
              name: data
              subPath: bazarr/config
            - mountPath: /tv
              name: data
              subPath: plex/data/tvshows
            - mountPath: /movies
              name: data
              subPath: plex/data/movies
          env:
            - name: PUID
              value: "0"
            - name: PGID
              value: "0"
            - name: TZ
              value: "America/New_York"
---
kind: Service
apiVersion: v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: bazarr
  annotations:
    metallb.universe.tf/address-pool: vlan-main
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 6767
  selector:
    name: bazarr
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plex-bazarr-ingress-tls
  namespace: {{ .Release.Namespace }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - bazarr.wg.sclem.dev
      secretName: letsencrypt-bazarr
  rules:
  - host: bazarr.wg.sclem.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bazarr
            port:
              name: http
