---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: plex-pvc
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
