apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
spec:
  chart:
    spec:
      chart: external-dns
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
      version: 1.10.1
  interval: 24h
  valuesFrom:
  - kind: ConfigMap
    name: external-dns-values-common
    valuesKey: values.yaml
  - kind: ConfigMap
    name: external-dns-values-env
    valuesKey: values.yaml
