helmCharts:
- name: redis
  releaseName: redis
  version: 17.3.6
  repo: https://charts.bitnami.com/bitnami
  valuesInline:
    fullnameOverride: redis
    architecture: standalone
    auth:
      enabled: false
    master:
      persistence:
        enabled: true
        storageClass: local-storage
        accessModes:
          - ReadWriteOnce
        size: 8Gi
    tls:
      enabled: false

resources:
- ./pv.yaml
