apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis
spec:
  local:
    path: /data/raid/k8s/redis
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: sclem.dev/storage-host
          operator: Exists
