namespace: home

components:
- ../../apps/unifi

resources:
- ./config/ingress.yaml

patchesStrategicMerge:
- |-
  apiVersion: v1
  kind: Service
  metadata:
    name: unifi
  spec:
    type: LoadBalancer
    loadBalancerIP: 192.168.1.254

- |-
  apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: unifi
  spec:
    local:
      path: /data/raid/k8s/home/unifi/config
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: sclem.dev/storage-host
            operator: Exists
