apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zigbee2mqtt
spec:
  chart:
    spec:
      chart: zigbee2mqtt
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      version: 9.4.2
  interval: 24h
  valuesFrom:
  - kind: ConfigMap
    name: zigbee2mqtt-values-common
    valuesKey: values.yaml
  - kind: ConfigMap
    name: zigbee2mqtt-values-env
    valuesKey: values.yaml
