apiVersion: v1
kind: PersistentVolume
metadata:
  name: zigbee2mqtt-data
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: zigbee2mqtt-data
    namespace: iot
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem
