namespace: headscale

components:
- ../apps/headscale
- ../apps/postgresql

configMapGenerator:
- name: headscale-config
  behavior: replace
  files:
  - config/config.yaml
- name: headscale-acl
  behavior: replace
  files:
  - config/acl.hujson
- name: postgresql-values-env
  files:
  - values.yaml=config/postgres-values.yaml

secretGenerator:
- name: headscale-private-key
  behavior: replace
  files:
  - config/key
- name: headscale-env
  behavior: replace
  envs:
  - config/headscale.env

resources:
- ./namespace.yaml
- ./service-headscale-stun.yaml
- ./config/ingress.yaml

patchesStrategicMerge:
- |-
  kind: Deployment
  apiVersion: apps/v1
  metadata:
    name: headscale
  spec:
    template:
      spec:
        tolerations:
          - key: cloud
            operator: Exists
            effect: NoExecute
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: cloud
                  operator: In
                  values:
                  - oracle
