namespace: headscale

components:
- ../apps/headscale
- ../apps/postgresql
- ../apps/derp

configMapGenerator:
- name: headscale-config
  behavior: replace
  files:
  - config/config.yaml
  - config/acl.yaml
  - config/derpmap.yaml
- name: postgresql-values-env
  files:
  - values.yaml=config/postgres-values.yaml
- name: derp-config
  behavior: merge
  envs:
  - config/derp.env

secretGenerator:
- name: headscale-private-key
  behavior: replace
  files:
  - key=config/key
  - noise-key=config/noise.key
- name: headscale-env
  behavior: replace
  envs:
  - config/headscale.env

resources:
- ./namespace.yaml
- ./config/ingress.yaml
- ./config/derp-cert.yaml
- ./config/derp-service.yaml

patchesStrategicMerge:
- |-
  kind: Deployment
  apiVersion: apps/v1
  metadata:
    name: headscale
  spec:
    template:
      spec:
        tolerations:
          - key: cloud
            operator: Exists
            effect: NoExecute
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: cloud
                  operator: In
                  values:
                  - oracle
- ./patches/deployment-derp.yaml
