
configMapGenerator:
- name: coredns-custom
  namespace: kube-system
  files:
  - config/coredns-custom.server
  options:
    disableNameSuffixHash: true

resources:
- metallb
- ingress-nginx
- cert-manager
- gpu-operator
- external-dns
