kind: Deployment
apiVersion: apps/v1
metadata:
  name: bazarr
  labels:
    app: plex
spec:
  selector:
    matchLabels:
      name: bazarr
  template:
    metadata:
      labels:
        name: bazarr
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: plex-pvc
      containers:
        - name: bazarr
          ports:
            - containerPort: 6767
          image: ghcr.io/k8s-at-home/bazarr
          volumeMounts:
            - mountPath: /config
              name: data
              subPath: bazarr/config
            - mountPath: /tv
              name: data
              subPath: plex/data/tvshows
            - mountPath: /movies
              name: data
              subPath: plex/data/movies
          env:
            - name: TZ
              value: "America/New_York"
