apiVersion: v1
kind: PersistentVolume
metadata:
  name: heimdall-config
spec:
  local:
    path: /data/raid/k8s/home/heimdall/config
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: sclem.dev/storage-host
          operator: Exists
