kind: Kustomization

namespace: dev

components:
- ../../apps/gitlab-runner

secretGenerator:
- name: gitlab-runner-s3
  envs:
  - config/s3.env
  options:
    disableNameSuffixHash: true
- name: gitlab-runner-token
  envs:
  - config/token.env
  options:
    disableNameSuffixHash: true

configMapGenerator:
- name: gitlab-runner-values-env
  files:
  - config/values.yaml
