secretGenerator:
- name: cloudflare-token
  namespace: kube-system
  envs:
  - config/cloudflare-token.env
  options:
    disableNameSuffixHash: true

resources:
- ./config/metallb-pools.yaml
- ./config/cluster-issuer.yaml
- ./config/wildcard-cert.yaml
- ./storageclass.yaml
- ./plex-pv.yaml
