---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default
  namespace: metallb-system
spec:
  addresses:
  - 192.168.1.32/27
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: skynet
  namespace: metallb-system
spec:
  autoAssign: false
  addresses:
  - 192.168.3.32/27
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: tailscale
  namespace: metallb-system
spec:
  autoAssign: false
  addresses:
  - 100.64.0.6/32
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: static
  namespace: metallb-system
spec:
  autoAssign: false
  addresses:
  - 192.168.1.254/32
  - 192.168.4.200/32
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default
  namespace: metallb-system
spec:
  ipAddressPools:
  - default
  - skynet
  - static
  nodeSelectors:
  - matchExpressions:
    - {key: cloud, operator: DoesNotExist}
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: tailscale
  namespace: metallb-system
spec:
  ipAddressPools:
  - tailscale
  nodeSelectors:
  - matchLabels:
      kubernetes.io/hostname: videx
