apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 3Ti
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: plex-pvc
    namespace: plex
  local:
    path: /data/raid/k8s/plex
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: sclem.dev/storage-host
          operator: Exists
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem
