coredns:
  namespace: kube-system
  loadBalancerIP: 192.168.1.54

certmanager:
  namespace: cert-manager
  email: ""
  cloudflareAPIToken: ""

persistence:
  plex:
    path: /data/raid/k8s/plex
    size: 3Ti
    host: videx
  home:
    path: /data/raid/k8s/home
    size: 3Ti
    host: videx
  cloud:
    path: /data/k8s/cloud
    size: 15Gi
    host: cloud

tunnel:
  credentials: ""
  ingress: []
