apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: default-tls-cert
spec:
  secretName: default-tls-cert
  commonName: COMMON_NAME
  dnsNames:
  - "DOMAIN"
  - "*.DOMAIN"
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
