namespace: iot

components:
- ../../apps/frigate

secretGenerator:
- name: basic-auth-frigate
  files:
  - config/auth
  type: Opaque

configMapGenerator:
- name: frigate
  behavior: replace
  files:
  - config.yml=config/config.yaml

resources:
- config/ingress.yaml
- pv.yaml
