namespace: iot

components:
- ../../apps/frigate

secretGenerator:
- name: basic-auth-frigate
  files:
  - config/auth
  type: Opaque
- name: regcred
  files:
  - config/.dockerconfigjson
  type: kubernetes.io/dockerconfigjson

configMapGenerator:
- name: frigate
  behavior: replace
  files:
  - config.yml=config/config.yaml

resources:
- config/ingress.yaml
- pv.yaml
- config/custom-clip.yaml
