kind: Deployment
apiVersion: apps/v1
metadata:
  name: registry
spec:
  selector:
    matchLabels:
      name: registry
  template:
    metadata:
      labels:
        name: registry
    spec:
      enableServiceLinks: false
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
      volumes:
      - name: certs
        secret:
          secretName: registry-keycloak
      containers:
        - name: registry
          ports:
            - containerPort: 5000
          image: docker.io/registry:2
          envFrom:
            - secretRef:
                name: registry-s3
          volumeMounts:
          - name: certs
            mountPath: /opt/certs
            readOnly: true
