namespace: storage

components:
- ../../apps/registry

secretGenerator:
- name: registry-s3
  behavior: replace
  envs:
  - config/registry.env
- name: registry-keycloak
  behavior: replace
  files:
  - config/trust_chain.pem

resources:
- config/ingress.yaml
