apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 3Ti
  claimRef:
    kind: PersistentVolumeClaim
    name: minio
    namespace: storage
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem
