apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: csi-vultr-controller
  namespace: kube-system
spec:
  template:
    spec:
      tolerations:
        - key: cloud
          operator: Exists
          effect: NoExecute
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: cloud
                operator: In
                values:
                - vultr
