kind: Service
apiVersion: v1
metadata:
  name: cups
spec:
  loadBalancerIP: 192.168.3.63
  type: LoadBalancer
  selector:
    app: cups
  ports:
  - name: cups
    port: 631
    targetPort: 631
    protocol: TCP
