apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
spec:
  chart:
    spec:
      chart: prometheus
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: prometheus
        namespace: flux-system
      version: 19.0.2
  interval: 24h
  valuesFrom:
  - kind: ConfigMap
    name: prometheus-values-common
    valuesKey: values.yaml
  - kind: ConfigMap
    name: prometheus-values-env
    valuesKey: values.yaml
