kind: Deployment
apiVersion: apps/v1
metadata:
  name: tinyproxy
spec:
  selector:
    matchLabels:
      name: tinyproxy
  template:
    metadata:
      labels:
        name: tinyproxy
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: tinyproxy
          image: registry.gitlab.com/kalaksi-containers/tinyproxy:1.3
          ports:
            - containerPort: 8888
          env:
            - name: ALLOWED_NETWORKS
              value: "0.0.0.0/0"
            - name: DISABLE_VIA_HEADER
              value: "yes"
            - name: MAX_CLIENTS
              value: "100"
            - name: MAX_SPARE_SERVERS
              value: "100"
            - name: MIN_SPARE_SERVERS
              value: "50"
