kind: Service
apiVersion: v1
metadata:
  name: tinyproxy
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8888
      # curl default port for proxy is 1080
    - name: http-curl
      port: 1080
      protocol: TCP
      targetPort: 8888
  selector:
    name: tinyproxy
