namespace: home

components:
- ../../apps/filebrowser

configMapGenerator:
- name: filebrowser-values-env
  files:
  - config/values.yaml

secretGenerator:
- name: yubikey-cert
  files:
  - config/ca.crt
  options:
    disableNameSuffixHash: true

resources:
- ./pv.yaml
- ./config/ingress-wan.yaml
