namespace: iot

configMapGenerator:
- name: zigbee2mqtt-domain
  envs:
  - config/domain.env

helmCharts:
- name: zigbee2mqtt
  repo: https://k8s-at-home.com/charts/
  version: 9.4.2
  releaseName: zigbee2mqtt
  namespace: iot
  valuesInline:
    ingress:
      main:
        enabled: true
        ingressClassName: nginx-lan
        hosts:
          - host: ZIGBEE2MQTT_HOST
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - ZIGBEE2MQTT_HOST
    persistence:
      data:
        enabled: true
        accessMode: ReadWriteOnce
        storageClass: local-storage
        size: 1Gi
      usb:
        enabled: true
        type: hostPath
        hostPath: /dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20220817114419-if00
        hostPathType: CharDevice
        mountPath: /dev/zigbee0
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - videx
    securityContext:
      privileged: true
    config:
      advanced:
        channel: 20
      homeassistant: true
      mqtt:
        base_topic: zigbee2mqtt
        server: 'mqtt://mqtt'
      serial:
        port: /dev/zigbee0
        adapter: ezsp

resources:
- pv.yaml

replacements:
- source:
    kind: ConfigMap
    name: zigbee2mqtt-domain
    fieldPath: data.DOMAIN
  targets:
  - select:
      kind: Ingress
      name: zigbee2mqtt
    fieldPaths:
    - spec.rules.0.host
    - spec.tls.0.hosts.0
    options:
      create: true
