apiVersion: v1
kind: PersistentVolume
metadata:
  name: heimdall-config
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  claimRef:
    kind: PersistentVolumeClaim
    name: heimdall-config
    namespace: home
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem
