controller:
  ingressClassResource:
    default: false
    name: nginx-cloud
    controllerValue: k8s.io/ingress-nginx-cloud
  service:
    enabled: true
    annotations:
      metallb.universe.tf/address-pool: cloud
    externalTrafficPolicy: Local
  ingressClass: nginx-cloud
  nodeSelector:
    kubernetes.io/hostname: cloud
  tolerations:
  - key: cloud
    operator: Exists
    effect: NoExecute
  dnsPolicy: ClusterFirstWithHostNet
  kind: DaemonSet
  publishService:
    enabled: true
