controller:
  ingressClassResource:
    default: false
    name: nginx-cloud
    controllerValue: k8s.io/ingress-nginx-cloud
  service:
    enabled: false
  ingressClass: nginx-cloud
  nodeSelector:
    kubernetes.io/hostname: cloud
  tolerations:
    - key: cloud
      operator: Exists
      effect: NoExecute
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  kind: DaemonSet
  publishService:
    enabled: true
