controller:
  ingressClassResource:
    default: true
    name: nginx-lan
    controllerValue: k8s.io/ingress-nginx-lan
  service:
    enabled: true
    annotations:
      metallb.universe.tf/address-pool: skynet
    externalTrafficPolicy: Local
  dnsPolicy: ClusterFirstWithHostNet
  kind: DaemonSet
  publishService:
    enabled: true
