controller:
  ingressClassResource:
    default: false
    name: nginx-wg
    controllerValue: k8s.io/ingress-nginx-wg
  service:
    enabled: true
    annotations:
      metallb.universe.tf/allow-shared-ip: "tailscale"
    loadBalancerIP: 100.64.0.6
  nodeSelector:
    kubernetes.io/hostname: videx
  dnsPolicy: ClusterFirstWithHostNet
  kind: DaemonSet
  publishService:
    enabled: true
