helmCharts:
- name: ingress-nginx
  repo: https://kubernetes.github.io/ingress-nginx
  namespace: ingress-nginx-lan
  version: 4.3.0
  releaseName: ingress-nginx-lan
  valuesInline:
    controller:
      ingressClassResource:
        default: true
        name: nginx-lan
        controllerValue: k8s.io/ingress-nginx-lan
      service:
        enabled: true
        annotations:
          metallb.universe.tf/address-pool: skynet
        externalTrafficPolicy: Local
      podAnnotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10254"
      metrics:
        enabled: true
      extraArgs:
        default-ssl-certificate: "default/default-tls-cert"
      kind: DaemonSet
      publishService:
        enabled: true

- name: ingress-nginx
  repo: https://kubernetes.github.io/ingress-nginx
  namespace: ingress-nginx-wg
  version: 4.3.0
  releaseName: ingress-nginx-wg
  valuesInline:
    controller:
      ingressClassResource:
        default: false
        name: nginx-wg
        controllerValue: k8s.io/ingress-nginx-wg
      service:
        enabled: true
        externalTrafficPolicy: Local
        loadBalancerIP: 100.64.0.6
      podAnnotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10254"
      metrics:
        enabled: true
      nodeSelector:
        kubernetes.io/hostname: videx
      extraArgs:
        default-ssl-certificate: "default/default-tls-cert"
      kind: DaemonSet
      publishService:
        enabled: true

- name: ingress-nginx
  repo: https://kubernetes.github.io/ingress-nginx
  version: 4.3.0
  namespace: ingress-nginx-cloud-oracle
  releaseName: ingress-nginx-cloud-oracle
  valuesInline:
    controller:
      ingressClassResource:
        default: false
        name: nginx-cloud-oracle
        controllerValue: k8s.io/ingress-nginx-cloud-oracle
      service:
        enabled: true
        type: NodePort
        nodePorts:
          http: 31080
          https: 31443
        externalTrafficPolicy: Local
        ipFamilyPolicy: RequireDualStack
        ipFamilies:
          - IPv4
          - IPv6
      podAnnotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10254"
      metrics:
        enabled: true
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: cloud
                operator: In
                values:
                - oracle
      ingressClass: nginx-cloud-oracle
      tolerations:
      - key: cloud
        operator: Exists
        effect: NoExecute
      kind: DaemonSet
      publishService:
        enabled: false
