apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitlab-runner
spec:
  chart:
    spec:
      chart: gitlab-runner
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: gitlab
        namespace: flux-system
      version: 0.46.1
  interval: 24h
  valuesFrom:
  - kind: ConfigMap
    name: gitlab-runner-values-common
    valuesKey: values.yaml
  - kind: ConfigMap
    name: gitlab-runner-values-env
    valuesKey: values.yaml
