namespace: iot

components:
- ../../apps/homeassistant
- ../../apps/hass-configurator

configMapGenerator:
- name: hass-configurator
  behavior: replace
  envs:
  - config/configurator.env

resources:
- ./pv.yaml
- ./service-wemo.yaml
- ./config/ingress.yaml
- ./config/ingress-configurator.yaml

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: StatefulSet
    name: hass
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: PYWEMO_CALLBACK_ADDRESS
        value: 192.168.4.200:8989
