kind: Deployment
apiVersion: apps/v1
metadata:
  name: transmission
  labels:
    app: plex
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: transmission
  template:
    metadata:
      labels:
        name: transmission
    spec:
      volumes:
        - name: wg-conf
          secret:
            secretName: vpn-wg-conf
        - name: data
          persistentVolumeClaim:
            claimName: plex-pvc
      initContainers:
        - name: flood-ui
          image: curlimages/curl:7.76.1
          command:
          - "/bin/sh"
          - "-c"
          - |-
            test ! -d /config/flood-for-transmission && \
              curl -o- -sL https://github.com/johman10/flood-for-transmission/releases/download/latest/flood-for-transmission.tar.gz | \
              tar xzf - -C /config || \
              exit 0
          volumeMounts:
          - name: data
            mountPath: /config
            subPath: transmission/config
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
      containers:
        - name: vpn
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - SYS_MODULE
            privileged: true
          image: ghcr.io/k8s-at-home/wireguard
          volumeMounts:
            - mountPath: /etc/wireguard/wg0.conf
              name: wg-conf
              subPath: conf
          env:
            - name: KILLSWITCH
              value: "true"
            - name: KILLSWITCH_EXCLUDEDNETWORKS_IPV4
              value: "10.42.0.0/16;10.43.0.0/16"
            - name: KILLSWITCH_EXCLUDEDNETWORKS_IPV6
              value: "fd10:c0de:42::/56;fd10:c0de:43::/112"
        - name: transmission
          image: ghcr.io/k8s-at-home/transmission
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
          ports:
            - containerPort: 9091
          envFrom:
            - configMapRef:
                name: transmission-env
          env:
            - name: TRANSMISSION_PEER_PORT
              valueFrom:
                secretKeyRef:
                  name: vpn-wg-conf
                  key: forward-port
            - name: TRANSMISSION_WEB_HOME
              value: /config/flood-for-transmission/
            - name: TZ
              value: "America/New_York"
          volumeMounts:
            - mountPath: /config
              name: data
              subPath: transmission/config
            - mountPath: /downloads
              name: data
              subPath: transmission/downloads
