namespace: plex

configMapGenerator:
- name: transmission-env
  envs:
  - config/transmission.env

secretGenerator:
- name: vpn-wg-conf
  files:
  - conf=config/wg0.conf
  envs:
  - config/vpn-port.env

resources:
- deployment.yaml
- service.yaml
- ingress.yaml
